# SPDX-License-Identifier: GPL-2.0-only
obj-$ (CONFIG_MDSS_PLL) += mdss-pll-util.o
obj-$(CO NFIG_MDSS_PLL) += mdss-pll.o
obj-$(CONFIG_MDS S_PLL) += mdss-dsi-pll-14nm.o
obj-$(CONFIG_MD SS_PLL) += mdss-dsi-pll-14nm-util.o
obj-$(CON FIG_MDSS_PLL) += mdss-dp-pll-14nm.o
obj-$(CON FIG_MDSS_PLL) += mdss-dsi-pll-28lpm.o
obj-$(C ONFIG_MDSS_PLL) += mdss-dsi-pll-28nm-util.o
o bj-$(CONFIG_MDSS_PLL) += mdss-dsi-pll-12nm.o obj-$(CONFIG_MDSS_PLL) += mdss-dsi-pll-12nm-u til.o  
ccflags-y += -I$(srctree)/$(src)
