# SPDX-License-Identifier: GPL-2.0-only

ccfl ags-y += -I$(srctree)/techpack/camera-xiaomi- cas/include/uapi
ccflags-y += -I$(srctree)/te chpack/camera-xiaomi-cas/drivers/cam_req_mgr/ 
ccflags-y += -I$(srctree)/techpack/camera-xi aomi-cas/drivers/cam_utils
ccflags-y += -I$(s rctree)/techpack/camera-xiaomi-cas/drivers/ca m_cpas/include
ccflags-y += -I$(srctree)/tech pack/camera-xiaomi-cas/drivers/cam_sensor_mod ule/cam_sensor_io
ccflags-y += -I$(srctree)/t echpack/camera-xiaomi-cas/drivers/cam_sensor_ module/cam_sensor_utils
ccflags-y += -I$(srct ree)/techpack/camera-xiaomi-cas/drivers/cam_s mmu
ccflags-y += -I$(srctree)

obj-$(CONFIG_S PECTRA_CAMERA) += cam_cci_dev.o cam_cci_core. o cam_cci_soc.o  
ccflags-y += -I$(srctree)/$(src)
