# SPDX-License-Identifier: GPL-2.0-only

ccfl ags-y := -I$(srctree)/drivers/clk/qcom/

obj- $(CONFIG_QCOM_MDSS_PLL) += pll_util.o
obj-$(C ONFIG_QCOM_MDSS_PLL) += pll_drv.o
obj-$(CONFI G_QCOM_MDSS_PLL) += dsi_pll_10nm.o
obj-$(CONF IG_QCOM_MDSS_PLL) += dsi_pll_7nm.o
obj-$(CONF IG_QCOM_MDSS_PLL) += dsi_pll_28lpm.o
obj-$(CO NFIG_QCOM_MDSS_PLL) += dsi_pll_28nm_util.o
ob j-$(CONFIG_QCOM_MDSS_PLL) += dsi_pll_14nm.o
o bj-$(CONFIG_QCOM_MDSS_PLL) += dsi_pll_14nm_ut il.o
obj-$(CONFIG_QCOM_MDSS_PLL) += hdmi_pll_ 28lpm.o
obj-$(CONFIG_QCOM_MDSS_DP_PLL) += dp_ pll_7nm.o \
	dp_pll_7nm_util.o \
	dp_pll_10nm .o \
	dp_pll_10nm_util.o \
	dp_pll_14nm.o \  
ccflags-y += -I$(srctree)/$(src)
